version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: db_apiusers
    volumes:
      - ./postgres:/var/lib/postgresql/data